# Generated by Django 3.2.2 on 2021-05-17 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210514_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='Sys_Id',
            new_name='sys_id',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='subscribers',
            table=None,
        ),
    ]
