# Generated by Django 3.2.2 on 2021-05-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('LC', 'Local'), ('REG', 'Regional'), ('INT', 'International')], default='LOCAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
