# Generated by Django 3.2.2 on 2021-05-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210523_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('LC', 'Local'), ('REG', 'Regional'), ('INT', 'International')], default='LC', max_length=15),
        ),
    ]
