# Generated by Django 3.2.2 on 2021-05-18 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_sub', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=150, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
